name: sgxl
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.11
  - pip
  - numpy>=1.26
  - click>=8.1
  - pillow=10.1.0
  - scipy=1.11.4
  - pytorch=2.1.2
  - requests=2.31.0
  - tqdm=4.66.1
  - ninja=1.11.1
  - matplotlib=3.8.2
  - imageio=2.33.0
  - dill=0.3.8
  - psutil=5.9.7
  - regex=2023.12.25
  - pip:
    - imgui==2.0.0
    - glfw==2.6.4
    - pyopengl==3.1.7
    - imageio-ffmpeg==0.4.9
    - pyspng
    - ftfy==6.1.3
    - timm==0.4.12
